### PR TITLE
Docs: Added Flux D1 Reference Architecture Guide

### PR DESCRIPTION
**Pull request by rowan-baker**
The purpose of this guide is to provide a comprehensive description of the Flux d1 reference architecture, provided by the d1 repos within the [controlplaneio-fluxcd](https://github.com/controlplaneio-fluxcd) organisation.

These repos and accompanying guide, build upon the existing Flux documentation, which features a quickstart guide orchestrating a single cluster, to demonstrate how Flux can address the needs of organisations with multiple teams looking to deploy applications on multiple multi-tenant Kubernetes clusters using Flux

### CODE REVIEW

**Comment by mestadler** [comment]
I cant approved the PR in githib but its approved officially by me.  Lets get it public!

**Review by dialmformart — APPROVED** [review]
LGTM

**Review by dialmformart — APPROVED** [review]

**Review by miguelangelher — APPROVED** [review]
Approved by Martin. The document have been triple reviewed at this point by Eduardo, Rowan, and the authors in a second read.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks to all involved 🏅

**Comment by souleb** [comment]
maybe we could link from the `README`.

**Comment by stefanprodan** [comment]
@souleb this needs to be linked from all readme files, in this repo and all D1 repos. We also need to write an intro and tell people about this doc, also a blog post in CP website.

**Pull request merged**
